language: cpp
compiler:
  - gcc
  - clang
dist: trusty
sudo: required

script: 
        - ./bootstrap.sh
        - mkdir build && cd build
        - ../configure
        - make
        - ./drachtio --version 
        -   npm test

git:
    submodules: false

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install gcc g++ build-essential make git autoconf curl libz-dev ncurses-dev libpcap-dev
    - sudo chmod 0777 /usr/local/src && cd /usr/local/src
    - git clone https://github.com/SIPp/sipp.git && cd sipp && git checkout v3.5.1 
    - ./build.sh  --with-rtpstream --with-pcap 
    - sudo make install
    - sudo apt-get install -y libcurl4-openssl-dev
    - sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
    - sudo apt-get install -y nodejs
    - curl-config --version
    - curl-config --libs 
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive